apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: service-registry
          image: harbor.sorakh.io/project-ciftp/registry-service:main
          ports:
            - containerPort: 8761
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: api-gateway-service
          envFrom:
            - configMapRef:
                name: ciftp-env
          image: harbor.sorakh.io/project-ciftp/api-gateway-service:main
          ports:
          - containerPort: 8765
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: auth-service
          image: harbor.sorakh.io/project-ciftp/auth-service:main
          envFrom:
            - configMapRef:
                name: ciftp-env
          env:
            - name: "DB_USER"
              value: "${AUTH_DB_USER}"
            - name: DB_PASSWORD
              value: "${AUTH_DB_PASSWORD}"

      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participant-service
  template:
    metadata:
      labels:
        app: participant-service
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
      - name: participant-service
        image: harbor.sorakh.io/project-ciftp/participant-service:main
        envFrom:
          - configMapRef:
              name: ciftp-env
        env:
        - name: DB_USER
          value: "${PARTICIPANT_DB_USER}"
        - name: DB_PASSWORD
          value: "${PARTICIPANT_DB_PASSWORD}"

      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-change-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-change-service
  template:
    metadata:
      labels:
        app: request-change-service
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
      - name: request-change-service
        image: harbor.sorakh.io/project-ciftp/ciftp-core-rqc:main
        envFrom:
          - configMapRef:
              name: ciftp-env
        env:
        - name: DB_USER
          value: "${RQC_DB_USER:}"
        - name: DB_PASSWORD
          value: "${RQC_DB_PASSWORD}"

      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: notification-service
          image: harbor.sorakh.io/project-ciftp/notification-service:main
          envFrom:
          - configMapRef:
              name: ciftp-env
          env:
            - name: DB_USER
              value: "${NOTIFICATION_USER}"
            - name: DB_PASSWORD
              value: "${NOTIFICATION_PASSWORD}"
      restartPolicy: Always


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: transaction-service
          image: harbor.sorakh.io/project-ciftp/transaction-service:main
          envFrom:
          - configMapRef:
              name: ciftp-env
          env:
            - name: DB_USER
              value: "${TRX_USER}"
            - name: DB_PASSWORD
              value: "${TRX_USER_PASSWORD}"
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: frontend-service
          image: harbor.sorakh.io/project-ciftp/ciftp-core-frontend:1.0.0-rc-6
          envFrom:
          - configMapRef:
              name: ciftp-env
          env:
            - name: BACKEND_ADDR
              value: "http://10.10.200.218:30001"
            # Add other environment variables from *x-platform-manifest here
          ports:
            - containerPort: 80
      restartPolicy: Always

