apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
    containers:
    - name: service-registry
      image: https://harbor.sorakh.io/project-ciftp/registry-service:main
      ports:
      - containerPort: 8761
    restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: https://harbor.sorakh.io/project-ciftp/api-gateway-service:main
        ports:
        - containerPort: 8765
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: https://harbor.sorakh.io/project-ciftp/auth-service:main
          env:
            - name: DB_USER
              value: "${AUTH_DB_USER}"
            - name: DB_PASSWORD
              value: "${AUTH_DB_PASSWORD}"

      restartPolicy: Always
  dependsOn:
    - name: service-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participant-service
  template:
    metadata:
      labels:
        app: participant-service
    spec:
      containers:
      - name: participant-service
        image: https://harbor.sorakh.io/project-ciftp/participant-service:main
        env:
        - name: DB_USER
          value: "${PARTICIPANT_DB_USER}"
        - name: DB_PASSWORD
          value: "${PARTICIPANT_DB_PASSWORD}"

      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-change-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-change-service
  template:
    metadata:
      labels:
        app: request-change-service
    spec:
      containers:
      - name: request-change-service
        image: https://harbor.sorakh.io/project-ciftp/ciftp-core-rqc:main
        env:
        - name: DB_USER
          value: "${RQC_DB_USER:}"
        - name: DB_PASSWORD
          value: "${RQC_DB_PASSWORD}"

      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: https://harbor.sorakh.io/project-ciftp/notification-service:main
          env:
            - name: DB_USER
              value: "${NOTIFICATION_USER}"
            - name: DB_PASSWORD
              value: "${NOTIFICATION_PASSWORD}"
            - name: MAIL_HOST
              value: "${MAIL_HOST}"
            - name: MAIL_PORT
              value: "${MAIL_PORT}"
            - name: MAIL_USER
              value: "${MAIL_USER}"
            - name: MAIL_PASSWORD
              value: "${MAIL_PASSWORD}"
            - name: MAIL_SSL_ENABLE
              value: "${MAIL_SSL_ENABLE:-true}"
      restartPolicy: Always
  dependsOn:
    - name: service-registry


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: https://harbor.sorakh.io/project-ciftp/transaction-service:main
          env:
            - name: DB_USER
              value: "${TRX_USER}"
            - name: DB_PASSWORD
              value: "${TRX_USER_PASSWORD}"
      restartPolicy: Always
  dependsOn:
    - name: service-registry

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: https://harbor.sorakh.io/project-ciftp/ciftp-core-frontend:1.0.0-rc-6
          env:
            - name: BACKEND_ADDR
              value: "${BACKEND_ADDR}"
            # Add other environment variables from *x-platform-manifest here
          ports:
            - containerPort: 80
      restartPolicy: Always
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

