apiVersion: v1
kind: Service
metadata:
  name: frontend-service-service
spec:
  selector:
    app: frontend-service-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
