apiVersion: v1
kind: Service
metadata:
  name: transaction-service-service
spec:
  selector:
    app: transaction-service-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
